/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Свободен ли логин (проверка на лету при регистрации) */
        get: operations["loginAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация (и вход) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход. Неверная пара логин/пароль не раскрывает, какое поле ошибочно */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход (сессия закрывается) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить профиль (имя, цвет, норма воды) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/couple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние пары (нет партнёра / входящий запрос / вместе) */
        get: operations["getCouple"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Настройки пары (часовой пояс) */
        patch: operations["updateCouple"];
        trace?: never;
    };
    "/couple/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ввести код партнёра (создаёт входящий запрос у владельца кода) */
        post: operations["joinCouple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couple/requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принять запрос в пару (данные пар объединяются) */
        post: operations["acceptRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couple/requests/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отклонить запрос */
        post: operations["declineRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Банки пары (новые сверху) */
        get: operations["listDrinks"];
        put?: never;
        /** Добавить банку */
        post: operations["createDrink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drinks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Банка по id */
        get: operations["getDrink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drinks/{id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Оценки банки (обеих сторон пары, новые сверху) */
        get: operations["listRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Поставить оценку (каждая оценка — новая запись, история сохраняется) */
        post: operations["createRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Записи «выпил» пары (новые сверху) */
        get: operations["listIntakes"];
        put?: never;
        /**
         * Записать «выпил»
         * @description Лимит — 2 энергетика в день на человека. Третью (и далее) можно записать только с `over_limit: true`,
         *     иначе 409 `limit_exceeded`. Флаг при записи в пределах лимита и для не-энергетиков игнорируется (сохраняется `false`):
         *     так записи из офлайн-очереди, пришедшие не по порядку, не ломаются.
         *     Неэнергетики (`is_energy: false`) в счёт не идут.
         */
        post: operations["createIntake"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intakes/day-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сколько энергетиков выпито за день (по умолчанию — сегодня по часам пары) */
        get: operations["getDaySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Вода за день текущего пользователя (по умолчанию — сегодня) */
        get: operations["getWater"];
        put?: never;
        /** Записать порцию воды (25..2000 мл) */
        post: operations["addWater"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water/glasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Свои стаканы текущего пользователя (до 3, объём 25..1000 мл) */
        get: operations["getWaterGlasses"];
        /** Заменить список своих стаканов целиком (идемпотентно) */
        put: operations["setWaterGlasses"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лента пары (новые сверху)
         * @description Только факты прямых действий обоих участников пары: выпитый энергетик, порция воды, закрытие дневной нормы воды.
         *     Записи «выпил» с `over_limit` в ленту попадают как обычные (пометку «сверх лимита» лента не показывает).
         *     Курсор непрозрачный.
         */
        get: operations["listFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description UUIDv7, создаёт клиент
         */
        Uuid: string;
        /**
         * Format: date-time
         * @description ISO-8601 UTC
         */
        Timestamp: string;
        /**
         * Format: date
         * @description День пары по её часовому поясу и границе суток
         */
        Day: string;
        /** @description Оценка в десятых (74 = 7.4) */
        Tenths: number;
        /** @enum {string} */
        Currency: "BYN" | "RUB";
        Money: {
            /** @description Минимальные единицы (копейки) */
            amount: number;
            currency: components["schemas"]["Currency"];
        };
        Problem: {
            /** @description URI типа; пока `about:blank` */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @enum {string} */
            code: "validation" | "unauthorized" | "not_found" | "id_conflict" | "login_taken" | "invalid_credentials" | "rate_limited" | "limit_exceeded" | "already_paired" | "invalid_code";
            /** @description Ошибки по полям (для `validation`) */
            errors?: {
                field: string;
                message: string;
            }[];
            /** @description Для `invalid_credentials` */
            attempts_left?: number;
            /** @description Для `rate_limited` */
            retry_after_seconds?: number;
        };
        LoginAvailability: {
            available: boolean;
            suggestions: string[];
        };
        RegisterRequest: {
            id: components["schemas"]["Uuid"];
            login: string;
            password: string;
        };
        LoginRequest: {
            login: string;
            password: string;
        };
        User: {
            id: components["schemas"]["Uuid"];
            login: string;
            display_name: string;
            /** @description Цвет игрока, #rrggbb */
            color: string;
            /** @default 2250 */
            water_goal_ml: number;
            couple_id: components["schemas"]["Uuid"];
            /** @description Личный код приглашения, например `EV-7429` */
            invite_code: string;
            created_at: components["schemas"]["Timestamp"];
        };
        UserPatch: {
            display_name?: string;
            color?: string;
            water_goal_ml?: number;
        };
        Couple: {
            id: components["schemas"]["Uuid"];
            /** @description IANA, например `Europe/Minsk` */
            timezone: string;
            /** @description Час, с которого начинается новый день (решено: 4 = с 04:00) */
            day_boundary_hour: number;
            members: components["schemas"]["Member"][];
        };
        Member: {
            id: components["schemas"]["Uuid"];
            display_name: string;
            color: string;
        };
        CoupleRequest: {
            id: components["schemas"]["Uuid"];
            from: components["schemas"]["Member"];
        };
        CoupleState: {
            /**
             * @description solo — партнёра нет; incoming — есть входящий запрос; paired — вместе
             * @enum {string}
             */
            status: "solo" | "incoming" | "paired";
            couple: components["schemas"]["Couple"];
            incoming_request?: components["schemas"]["CoupleRequest"];
            /** @description Вы ввели код партнёра и ждёте ответа */
            outgoing_pending?: boolean;
        };
        CouplePatch: {
            timezone?: string;
        };
        JoinRequest: {
            id: components["schemas"]["Uuid"];
            /** @description Код партнёра, регистр и дефис не важны */
            code: string;
        };
        Drink: {
            id: components["schemas"]["Uuid"];
            name: string;
            /** @description Название бренда (справочник брендов — отдельный блок, пока строка) */
            brand: string;
            is_energy: boolean;
            volume_ml: number;
            /** @description Сахар, десятые грамма на 100 мл; null — неизвестно */
            sugar_g_per_100ml?: number | null;
            /** @enum {string} */
            country: "BY" | "RU";
            created_by: components["schemas"]["Uuid"];
            created_at: components["schemas"]["Timestamp"];
        };
        DrinkCreate: {
            id: components["schemas"]["Uuid"];
            name: string;
            brand: string;
            /** @default true */
            is_energy?: boolean;
            volume_ml: number;
            sugar_g_per_100ml?: number | null;
            /** @enum {string} */
            country: "BY" | "RU";
        };
        DrinkPage: {
            items: components["schemas"]["Drink"][];
            next_cursor: string | null;
        };
        Rating: {
            id: components["schemas"]["Uuid"];
            drink_id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            smell: components["schemas"]["Tenths"];
            taste: components["schemas"]["Tenths"];
            after: components["schemas"]["Tenths"];
            strength: components["schemas"]["Tenths"];
            /** @description Среднее четырёх параметров, округлено до десятых (половина вверх); считает сервер */
            total: components["schemas"]["Tenths"];
            comment?: string | null;
            at: components["schemas"]["Timestamp"];
        };
        RatingCreate: {
            id: components["schemas"]["Uuid"];
            drink_id: components["schemas"]["Uuid"];
            smell: components["schemas"]["Tenths"];
            taste: components["schemas"]["Tenths"];
            after: components["schemas"]["Tenths"];
            strength: components["schemas"]["Tenths"];
            comment?: string | null;
            at?: components["schemas"]["Timestamp"];
        };
        Intake: {
            id: components["schemas"]["Uuid"];
            drink_id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            at: components["schemas"]["Timestamp"];
            local_day: components["schemas"]["Day"];
            over_limit: boolean;
        };
        IntakeCreate: {
            id: components["schemas"]["Uuid"];
            drink_id: components["schemas"]["Uuid"];
            at: components["schemas"]["Timestamp"];
            /** @default false */
            over_limit?: boolean;
        };
        IntakePage: {
            items: components["schemas"]["Intake"][];
            next_cursor: string | null;
        };
        DaySummary: {
            day: components["schemas"]["Day"];
            energy_count: number;
            /** @description Дневной лимит (2) */
            limit: number;
            /** @description В этот день была запись сверх лимита */
            over_limit: boolean;
        };
        WaterGlasses: {
            /** @description Объёмы своих стаканов, мл, без повторов */
            glasses: number[];
        };
        FeedItem: {
            /** @description Стабильный ключ элемента (не UUID: «норма закрыта» порождается записью воды) */
            id: string;
            /** @enum {string} */
            kind: "intake" | "water" | "water_goal";
            user_id: components["schemas"]["Uuid"];
            at: components["schemas"]["Timestamp"];
            drink_id?: components["schemas"]["Uuid"];
            /** @description Для kind=intake */
            drink_name?: string;
            /** @description Для kind=intake: итог оценки автора этой банки, десятые; null — не оценивал */
            score?: number | null;
            /** @description Для kind=water */
            ml?: number;
            /** @description Для kind=water_goal: норма автора на тот момент */
            goal_ml?: number;
        };
        FeedPage: {
            items: components["schemas"]["FeedItem"][];
            next_cursor: string | null;
        };
        WaterEntry: {
            id: components["schemas"]["Uuid"];
            user_id: components["schemas"]["Uuid"];
            ml: number;
            at: components["schemas"]["Timestamp"];
            local_day: components["schemas"]["Day"];
        };
        WaterCreate: {
            id: components["schemas"]["Uuid"];
            ml: number;
            at: components["schemas"]["Timestamp"];
        };
        WaterDay: {
            day: components["schemas"]["Day"];
            total_ml: number;
            goal_ml: number;
            goal_reached: boolean;
            entries: components["schemas"]["WaterEntry"][];
        };
    };
    responses: {
        /** @description Ошибка */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: components["schemas"]["Uuid"];
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginAvailable: {
        parameters: {
            query: {
                login: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результат; при занятом логине `suggestions` — до 3 свободных вариантов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginAvailability"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Повтор с тем же id (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Создан, сессия открыта */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Сессия открыта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Неверные данные (`code: invalid_credentials`, `attempts_left`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Блокировка после серии неудач (`code: rate_limited`, `retry_after_seconds`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Обновлённый профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getCouple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пара и состояние */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleState"];
                };
            };
        };
    };
    updateCouple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouplePatch"];
            };
        };
        responses: {
            /** @description Обновлённая пара */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleState"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    joinCouple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Запрос отправлен (повтор безопасен) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleState"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    acceptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вы вместе */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleState"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    declineRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Запрос отклонён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleState"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listDrinks: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrinkPage"];
                };
            };
        };
    };
    createDrink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrinkCreate"];
            };
        };
        responses: {
            /** @description Повтор с тем же id (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drink"];
                };
            };
            /** @description Создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drink"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getDrink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Банка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drink"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listRatings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"][];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingCreate"];
            };
        };
        responses: {
            /** @description Повтор с тем же id (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
            /** @description Создана; `total` считает сервер */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listIntakes: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Только за этот день пары (YYYY-MM-DD) */
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakePage"];
                };
            };
        };
    };
    createIntake: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeCreate"];
            };
        };
        responses: {
            /** @description Повтор с тем же id (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intake"];
                };
            };
            /** @description Записано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intake"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getDaySummary: {
        parameters: {
            query?: {
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сводка за день для текущего пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummary"];
                };
            };
        };
    };
    getWater: {
        parameters: {
            query?: {
                day?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сводка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
        };
    };
    addWater: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaterCreate"];
            };
        };
        responses: {
            /** @description Повтор с тем же id (идемпотентность) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterEntry"];
                };
            };
            /** @description Записано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterEntry"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getWaterGlasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterGlasses"];
                };
            };
        };
    };
    setWaterGlasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaterGlasses"];
            };
        };
        responses: {
            /** @description Сохранено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterGlasses"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    listFeed: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
        };
    };
}
